### ISSUE TITLE
会考虑支持Abp vnext不？

### ISSUE THREAD

**Issue by xewn** [GameBelial/Abp.Grpc#6]
abp vnext里没找到使用consul的开源方案。
同时rest api的自动生成和rest api client的自动生成。如果能整合在自动生成内，就比较方便了嗯。

**Comment by GameBelial** [comment]
目前也在关注 Abp vNext，但是 Abp vNext 还处于预览版状态，可能结构后期会发生重大变动，估计等它的 1.0 版本出来之后会后续跟进的。
