### ISSUE TITLE
请问服务接口实现应该如何使用依赖注入？

### ISSUE THREAD

**Issue by NepPure** [GameBelial/Abp.Grpc#7]
### 3.1.5 实现提供的服务接口

```csharp
public class MyService : ServiceBase<IMyService>,IMyService
{
    public UnaryResult<int> CalculateNumber(int x,int y)
    {
        return UnaryResult(x + y);
    }
}
```

关于实现服务接口，请问这里怎样才能使用ABP的依赖注入系统？
调用时的服务实例创建并没有被依赖注入容器管理，
IocManager.Instance.Resolve可用，但是对单元测试不友好，不知大佬是否有更好的办法？

**Comment by GameBelial** [comment]
@NepPure 该问题取决于 MagicOnion 作者这边的进度，因为需要更改其底层代码。现在该作者已经正在实现依赖注入功能，在 MagicOnion 库支持之后，我这边会立即更新的。

参考 Issue: [https://github.com/Cysharp/MagicOnion/issues/64](https://github.com/Cysharp/MagicOnion/issues/64)

**Comment by NepPure** [comment]
@GameBelial 感谢解答

**Comment by NepPure** [comment]
@GameBelial MagicOnion已经更新啦

**Comment by GameBelial** [comment]
@NepPure 好的，这边会跟进。

**Comment by GameBelial** [comment]
@NepPure https://github.com/GameBelial/Abp.Grpc/commit/50962a70d799bdf75e53526180a2725b2dcdc3db 已经集成依赖注入，请直接更新包版本即可.
