### ISSUE TITLE
如何在abpvnext中使用？

### ISSUE THREAD

**Issue by xewn** [GameBelial/Abp.Grpc#8]
我已经在正式环境中使用abp vnext了，拿了一个小产品尝试，还比较稳定，开发效率相对低一点。
考虑使用Abp.Grpc实现服务注册发现，方便开始支持abp vnext了不？有个简单的demo也要的。

**Comment by GameBelial** [comment]
@xewn  vNext 的版本还在开发中，大概下周末的时候会开一个新的仓库。

**Comment by xewn** [comment]
新仓库开了没？可以试用了不

**Comment by GameBelial** [comment]
@xewn 代码还在修改中，最近比较忙，好了会在 readme 更新的
